export enum EventStatus {
  UPCOMING = "UPCOMING",
  ONGOING = "ONGOING",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum EventCategory {
  EXHIBITION = "EXHIBITION",
  TRAINING = "TRAINING",
  DEALER_MEET = "DEALER_MEET",
  PRODUCT_LAUNCH = "PRODUCT_LAUNCH",
}
