-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "damagedQty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reorderLevel" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "reservedQty" INTEGER NOT NULL DEFAULT 0;
