name: Auto Deploy Backend

on:
  push:
    branches:
      - main  # আপনি যদি অন্য ব্রাঞ্চ ব্যবহার করেন তবে সেটি দিন

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/wood-server-hakim
            git pull origin main
            
            # pnpm এবং node এর পাথ সেট করা (যাতে কমান্ড খুঁজে পায়)
            export PATH=$PATH:/root/.local/share/pnpm:/usr/local/bin
            
            pnpm install
            pnpm build
            
            # PM2 দিয়ে রিস্টার্ট করা
            pm2 restart wood-server || pm2 start dist/server.js --name "wood-server"